### PR TITLE
Some updates to Setup

### PR DESCRIPTION
**Pull request by JimBrown**
Fixed typo in config.sample.ps1
Added BenchmarkInterval to Advanced tab
Added Power tab

### CODE REVIEW

**Comment by JimBrown** [comment]
Planned to work on the rest today, once you approved this one. ;-) Figured I'd add an "Advanced 2" tab (and rename the current "Advanced" to "Advanced 1").

**Comment by UselessGuru** [comment]
I would rather keep my extensions in an aptly named tab ;-)

**Comment by JimBrown** [comment]
Would it be ok if the tab header included your "aptly named" thing? ;-) Otherwise, the tab titles get a bit long.

**Comment by JimBrown** [comment]
All done. Hope it meets with your approval. (I'll know it does when it gets merged. ;-) )

**Comment by UselessGuru** [comment]
Thank you.

**Pull request merged**
