### PR TITLE
Spice up Profitability Display on Host

### PR DESCRIPTION
**Pull request by platinum4**
Gotta start the New Year off right!  Dope coloring on deck.

Fixed color: https://i.imgur.com/DnWzhAc.png

### CODE REVIEW

**Comment by platinum4** [comment]
Hey fool when are you gonna merge this shit to make this miner look DOPE AS FUCK

**Comment by platinum4** [comment]
Hey fool u need to wake on up and merge this shit right here right now

**Comment by hapklaar** [comment]
Indeed, this should be prio 1!

**Comment by platinum4** [comment]
UselessGuru is resistant to this badass Dope Coloring but he will Merge this because it is his chosen destiny

**Comment by UselessGuru** [comment]
I'll implement a config switch for this: $UseDopeColoring = $true

**Comment by platinum4** [comment]
That'd be a hell yeah

**Comment by UselessGuru** [comment]
Will be included in my next upload

Use $UseDopeColoring = $true switch in Config.ps1

**Pull request closed without merging**
